### ISSUE TITLE
[BUG] Demo The menu can not be displayed completely

### ISSUE THREAD

**Issue by kslr** [sinchang/vue-dplayer#1]

**Comment by sinchang** [comment]
It's aplayer bug, I already submited PR, but he not update latest version package to npm yet.

**Comment by kslr** [comment]
Okay, wait a little while.

Also, do I have to use the gulf management pack?

**Comment by sinchang** [comment]
I am using css to fix that right now.

**Comment by sinchang** [comment]
please update to 0.0.2

**Comment by kslr** [comment]
Thank you for your work
