### ISSUE TITLE
在vue2使用的时候发现有一个问题。在切换视频的时候，控制台报错。播放还是正常播放，就是进度条没有归零

### ISSUE THREAD

**Issue by aa1037673386** [sinchang/vue-dplayer#2]
![html](https://cloud.githubusercontent.com/assets/25314126/26274334/38c4004e-3d7a-11e7-8b87-792fbc9531b0.png)
![vuejs](https://cloud.githubusercontent.com/assets/25314126/26274335/397cc516-3d7a-11e7-8275-47804a6f1edf.png)
![default](https://cloud.githubusercontent.com/assets/25314126/26274340/504c84c0-3d7a-11e7-82c9-e24b8d691d48.png)

**Comment by sinchang** [comment]
你好，我模拟了你的情况，我的写法如下，是正常运行。
```js
    mounted() {
      this.player = this.$refs.player.dp
    },
    methods: {
      play() {
        console.log('play callback')
      },
      switchHandle() {
        this.player.switchVideo({
          url: 'http://static.smartisanos.cn/common/video/video-jgpro.mp4'
        })
      }
    },
```

**Comment by aa1037673386** [comment]
现在是不会报错了，我以为danmaku是必传。切换之后的时候，进度条还是没有归零



<template>
  <div>
    <div class="video-container clearfix">
      <div class="fl">
        
          
          
            
          
          
        
        <d-player
          class="MyVideo"
          ref="player"
          :video="videos"
          :lang="lang"
          :theme="theme"
          :hotkey="hotkey"
          :screenshot="screenshot"
          :loop="loop"
          :autoplay="autoplay"
          @ended="ended">
        </d-player>
      </div>
      
      <div class="videos fr">
        <div class="video-item" v-for="item in videoList">
          <div :src="item.attachUrl" @click="videoUrl(item)"></div>
          <p>{{item.title}}</p>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
  import VueDPlayer from 'vue-dplayer'
  export default {
    name:'ReviewVideo',
    props:['videoList'],
    components: {
      'd-player': VueDPlayer
    },
    data () {
      return {
//        videos: true,
        videos:{
          url:'http://ooflcbidd.bkt.clouddn.com//ls7pV6ot1gidsqN4Enysyp4KUfZw'
        },
        lang: "zh",               // 播放器语言
        theme: "blue",            // 播放器主题色
        hotkey: true,             // 绑定热键，包括左和右
        screenshot: false,        // 是否支持截图
        loop: false,              // 是否循环播放
        autoplay: false,          // 是否自动播放视频
//        preload: 'auto',          // 加载视频的方式可以是'无''元数据'或'自动'
      }
    },
    updated () {
//      this.videoPay();
    },
    methods: {
      videoPay () {
        let self = this;
//        if (self.videoList.length === 1) {
//          this.$refs.reviewVideo.style.width = '100%';
//        }
      },
      // 视频列表 点击更换播放地址
      videoUrl (item) {
        const player = this.$refs.player.dp;
        player.switchVideo({
          url: item.attachUrl
        });
//        player.play();

      },
      ended () {
        console.log('play callback')
      }
    }
  }
</script>

<style lang="less" scoped>
 .MyVideo {
   width: 720px;
   height: 424px;
 }
.video-container {
 margin-bottom: 20px;
 padding: 0 40px;
 .videos {
   width: 220px;
   height: 420px;
   overflow: auto;
   background: #ffffff;
   .video-item {
     text-align: center;
     div {
       margin: 8px auto 8px;
       background: #cccccc;
       width: 160px;
       height: 105px;
     }
   }
 }
} /*video-content*/
</style>

**Comment by aa1037673386** [comment]
可以了。但是切换之后，进度条还是没有归零。。

`<template>
  <div>
    <div class="video-container clearfix">
      <div class="fl">
        
          
          
            
          
          
        
        <d-player
          class="MyVideo"
          ref="player"
          :video="videos"
          :lang="lang"
          :theme="theme"
          :hotkey="hotkey"
          :screenshot="screenshot"
          :loop="loop"
          :autoplay="autoplay"
          @ended="ended">
        </d-player>
      </div>
      
      <div class="videos fr">
        <div class="video-item" v-for="item in videoList">
          <div :src="item.attachUrl" @click="videoUrl(item)"></div>
          <p>{{item.title}}</p>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
  import VueDPlayer from 'vue-dplayer'
  export default {
    name:'ReviewVideo',
    props:['videoList'],
    components: {
      'd-player': VueDPlayer
    },
    data () {
      return {
//        videos: true,
        videos:{
          url:'http://ooflcbidd.bkt.clouddn.com//ls7pV6ot1gidsqN4Enysyp4KUfZw'
        },
        lang: "zh",               // 播放器语言
        theme: "blue",            // 播放器主题色
        hotkey: true,             // 绑定热键，包括左和右
        screenshot: false,        // 是否支持截图
        loop: false,              // 是否循环播放
        autoplay: false,          // 是否自动播放视频
//        preload: 'auto',          // 加载视频的方式可以是'无''元数据'或'自动'
      }
    },
    updated () {
//      this.videoPay();
    },
    methods: {
      videoPay () {
        let self = this;
//        if (self.videoList.length === 1) {
//          this.$refs.reviewVideo.style.width = '100%';
//        }
      },
      // 视频列表 点击更换播放地址
      videoUrl (item) {
        const player = this.$refs.player.dp;
        player.switchVideo({
          url: item.attachUrl
        });
//        player.play();

      },
      ended () {
        console.log('play callback')
      }
    }
  }
</script>

<style lang="less" scoped>
 .MyVideo {
   width: 720px;
   height: 424px;
 }
.video-container {
 margin-bottom: 20px;
 padding: 0 40px;
 .videos {
   width: 220px;
   height: 420px;
   overflow: auto;
   background: #ffffff;
   .video-item {
     text-align: center;
     div {
       margin: 8px auto 8px;
       background: #cccccc;
       width: 160px;
       height: 105px;
     }
   }
 }
} /*video-content*/
</style>
`
