### ISSUE TITLE
在 ios 端不能进行播放

### ISSUE THREAD

**Issue by kuangwenping** [sinchang/vue-dplayer#3]
老师你好，我这边现在有这么一个情况：根据文档配置后，在ios端不能进行播放，我克隆下来后，就官方例子把服务起起来，ios端也不能进行播放，只显示封面图。想知道您部署到线上的例子是如何配置的，或者有什么解决的办法。   谢谢啦

**Comment by sinchang** [comment]
首先呢，不要把具体问题描述放到标题上，太丑了，标题要简洁。

再者希望提供下你的代码到 codepen 或者 jsbin。
